attempt to fix bug: AttributeError: 'Or' object has no attribute 'index' Since query may not contain index here, simply use a class method. Remake some tests for mock structures needed for execute.